<?php

namespace Container3y7R6sF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X6cwESOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x6cwESO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x6cwESO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hotelRepository' => ['privates', 'App\\Repository\\HotelRepository', 'getHotelRepositoryService', true],
            'roomRepository' => ['privates', 'App\\Repository\\Admin\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'hotelRepository' => 'App\\Repository\\HotelRepository',
            'roomRepository' => 'App\\Repository\\Admin\\RoomRepository',
        ]);
    }
}
