<?php

namespace Container3y7R6sF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..NfbVR8.App\Entity\Admin\Room' shared service.
     *
     * @return \App\Entity\Admin\Room
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..NfbVR8": it references class "App\\Entity\\Admin\\Room" but no such service exists.');
    }
}
