<?php

namespace Container3y7R6sF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Admin\RoomType' shared autowired service.
     *
     * @return \App\Form\Admin\RoomType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Admin/RoomType.php';

        return $container->privates['App\\Form\\Admin\\RoomType'] = new \App\Form\Admin\RoomType();
    }
}
