<?php

namespace ContainerCjsl3Ln;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SkjZD_7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.skjZD.7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.skjZD.7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roomRepository' => ['privates', 'App\\Repository\\Admin\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'roomRepository' => 'App\\Repository\\Admin\\RoomRepository',
        ]);
    }
}
