<?php

namespace ContainerCjsl3Ln;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4FbaXEtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4FbaXEt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4FbaXEt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\Admin\\CommentRepository', 'getCommentRepositoryService', true],
            'hotel' => ['privates', '.errored..service_locator.4FbaXEt.App\\Entity\\Hotel', NULL, 'Cannot autowire service ".service_locator.4FbaXEt": it references class "App\\Entity\\Hotel" but no such service exists.'],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
            'roomRepository' => ['privates', 'App\\Repository\\Admin\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\Admin\\CommentRepository',
            'hotel' => 'App\\Entity\\Hotel',
            'imageRepository' => 'App\\Repository\\ImageRepository',
            'roomRepository' => 'App\\Repository\\Admin\\RoomRepository',
        ]);
    }
}
