<?php

namespace ContainerCjsl3Ln;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5b7_g.Z.App\Entity\Setting' shared service.
     *
     * @return \App\Entity\Setting
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5b7_g.Z": it references class "App\\Entity\\Setting" but no such service exists.');
    }
}
