<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjsl3Ln\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjsl3Ln/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCjsl3Ln.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCjsl3Ln\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCjsl3Ln\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cjsl3Ln',
    'container.build_id' => '0b015dde',
    'container.build_time' => 1650106143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCjsl3Ln');
